import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { LineChart, Line, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, ReferenceDot } from "recharts";
import { Calendar, TrendingUp, AlertCircle, Sparkles, Target, DollarSign, Activity } from "lucide-react";

interface TimingDataPoint {
  date: string;
  projectedRevenue: number;
  impactScore: number;
  competitorActivity: number;
  marketDemand: number;
}

interface Recommendation {
  optimalDate: string;
  expectedRevenue: number;
  roi: number;
  confidence: number;
  riskLevel: "Low" | "Medium" | "High";
  rationale: string;
}

interface AlternativeDate {
  date: string;
  revenue: number;
  impactDelta: number;
  reason: string;
}

export function MarketTimingOptimizer() {
  const [eventName, setEventName] = useState("");
  const [strategyType, setStrategyType] = useState("");
  const [analyzing, setAnalyzing] = useState(false);
  const [showResults, setShowResults] = useState(false);

  const handleAnalyze = () => {
    setAnalyzing(true);
    setTimeout(() => {
      setAnalyzing(false);
      setShowResults(true);
    }, 2000);
  };

  // Sample data - would be generated by Gemini AI
  const timelineData: TimingDataPoint[] = [
    { date: "Week 1", projectedRevenue: 85000, impactScore: 65, competitorActivity: 40, marketDemand: 70 },
    { date: "Week 2", projectedRevenue: 92000, impactScore: 72, competitorActivity: 35, marketDemand: 75 },
    { date: "Week 3", projectedRevenue: 125000, impactScore: 95, competitorActivity: 20, marketDemand: 90 },
    { date: "Week 4", projectedRevenue: 118000, impactScore: 88, competitorActivity: 25, marketDemand: 85 },
    { date: "Week 5", projectedRevenue: 98000, impactScore: 75, competitorActivity: 45, marketDemand: 78 },
    { date: "Week 6", projectedRevenue: 88000, impactScore: 68, competitorActivity: 50, marketDemand: 72 },
    { date: "Week 7", projectedRevenue: 95000, impactScore: 73, competitorActivity: 38, marketDemand: 76 },
    { date: "Week 8", projectedRevenue: 110000, impactScore: 82, competitorActivity: 30, marketDemand: 82 },
  ];

  const recommendation: Recommendation = {
    optimalDate: "Week 3 (Jan 15-21, 2025)",
    expectedRevenue: 125000,
    roi: 187,
    confidence: 95,
    riskLevel: "Low",
    rationale: "Peak market demand aligns with minimal competitor activity. Historical data shows 23% higher conversion during this period. Sentiment analysis indicates positive market reception."
  };

  const alternativeDates: AlternativeDate[] = [
    { date: "Week 8", revenue: 110000, impactDelta: -12, reason: "Secondary peak with moderate competitor pressure" },
    { date: "Week 4", revenue: 118000, impactDelta: -6, reason: "Strong demand but increasing competition" },
    { date: "Week 2", revenue: 92000, impactDelta: -26, reason: "Early entry advantage but lower market readiness" },
  ];

  const scenarioData = [
    { scenario: "Best Case", revenue: 156000, probability: 25 },
    { scenario: "Expected", revenue: 125000, probability: 60 },
    { scenario: "Worst Case", revenue: 98000, probability: 15 },
  ];

  const peakDate = "Week 3";

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-3xl font-bold flex items-center gap-2">
          <Calendar className="h-8 w-8 text-primary" />
          Market Timing Optimizer
        </h2>
        <p className="text-muted-foreground mt-2">
          AI-powered timing prediction for strategic business moves. Launch at the exact profit-maximizing moment.
        </p>
      </div>

      {/* Input Section */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Target className="h-5 w-5" />
            Define Your Strategic Move
          </CardTitle>
          <CardDescription>Enter details about your planned business initiative</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="eventName">Event/Initiative Name</Label>
              <Input
                id="eventName"
                placeholder="e.g., Premium Product Launch"
                value={eventName}
                onChange={(e) => setEventName(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="strategyType">Strategy Type</Label>
              <Select value={strategyType} onValueChange={setStrategyType}>
                <SelectTrigger id="strategyType">
                  <SelectValue placeholder="Select strategy type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="product-launch">Product Launch</SelectItem>
                  <SelectItem value="marketing-campaign">Marketing Campaign</SelectItem>
                  <SelectItem value="pricing-change">Pricing Adjustment</SelectItem>
                  <SelectItem value="expansion">Market Expansion</SelectItem>
                  <SelectItem value="promotion">Promotional Campaign</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <Button 
            onClick={handleAnalyze} 
            disabled={!eventName || !strategyType || analyzing}
            className="w-full"
          >
            {analyzing ? (
              <>
                <Sparkles className="h-4 w-4 mr-2 animate-spin" />
                Analyzing Market Conditions...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4 mr-2" />
                Generate Optimal Timing
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {showResults && (
        <>
          {/* Optimal Timing Recommendation */}
          <Card className="border-primary/50 bg-primary/5">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-primary" />
                Recommended Launch Window
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="space-y-1">
                  <p className="text-sm text-muted-foreground">Optimal Date</p>
                  <p className="text-2xl font-bold text-primary">{recommendation.optimalDate}</p>
                </div>
                <div className="space-y-1">
                  <p className="text-sm text-muted-foreground flex items-center gap-1">
                    <DollarSign className="h-3 w-3" />
                    Expected Revenue
                  </p>
                  <p className="text-2xl font-bold">${recommendation.expectedRevenue.toLocaleString()}</p>
                </div>
                <div className="space-y-1">
                  <p className="text-sm text-muted-foreground">ROI</p>
                  <p className="text-2xl font-bold text-green-600">{recommendation.roi}%</p>
                </div>
                <div className="space-y-1">
                  <p className="text-sm text-muted-foreground">Risk Level</p>
                  <Badge variant={recommendation.riskLevel === "Low" ? "default" : "destructive"}>
                    {recommendation.riskLevel}
                  </Badge>
                  <p className="text-sm mt-1">{recommendation.confidence}% Confidence</p>
                </div>
              </div>
              <Separator />
              <div className="flex items-start gap-2">
                <Sparkles className="h-4 w-4 text-primary mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm font-medium">AI Rationale</p>
                  <p className="text-sm text-muted-foreground">{recommendation.rationale}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Timeline Graph */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-5 w-5" />
                Profit vs. Timeline Analysis
              </CardTitle>
              <CardDescription>Projected revenue and impact scores across all candidate launch dates</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={300}>
                <AreaChart data={timelineData}>
                  <defs>
                    <linearGradient id="revenueGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="hsl(var(--primary))" stopOpacity={0.3} />
                      <stop offset="95%" stopColor="hsl(var(--primary))" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                  <XAxis dataKey="date" className="text-xs" />
                  <YAxis className="text-xs" />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'hsl(var(--card))',
                      border: '1px solid hsl(var(--border))',
                      borderRadius: '8px'
                    }}
                  />
                  <Area 
                    type="monotone" 
                    dataKey="projectedRevenue" 
                    stroke="hsl(var(--primary))" 
                    strokeWidth={2}
                    fill="url(#revenueGradient)"
                  />
                  <ReferenceLine 
                    x={peakDate} 
                    stroke="hsl(var(--primary))" 
                    strokeDasharray="3 3" 
                    label={{ value: "Optimal Window", position: "top" }}
                  />
                  <ReferenceDot 
                    x={peakDate} 
                    y={125000} 
                    r={6} 
                    fill="hsl(var(--primary))" 
                    stroke="hsl(var(--background))"
                    strokeWidth={2}
                  />
                </AreaChart>
              </ResponsiveContainer>

              {/* Market Factors */}
              <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
                <Card className="bg-muted/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-medium">Market Demand</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ResponsiveContainer width="100%" height={80}>
                      <LineChart data={timelineData}>
                        <Line type="monotone" dataKey="marketDemand" stroke="hsl(var(--primary))" strokeWidth={2} dot={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  </CardContent>
                </Card>
                <Card className="bg-muted/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-medium">Impact Score</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ResponsiveContainer width="100%" height={80}>
                      <LineChart data={timelineData}>
                        <Line type="monotone" dataKey="impactScore" stroke="hsl(var(--chart-2))" strokeWidth={2} dot={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  </CardContent>
                </Card>
                <Card className="bg-muted/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-medium">Competitor Activity</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ResponsiveContainer width="100%" height={80}>
                      <LineChart data={timelineData}>
                        <Line type="monotone" dataKey="competitorActivity" stroke="hsl(var(--destructive))" strokeWidth={2} dot={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  </CardContent>
                </Card>
              </div>
            </CardContent>
          </Card>

          {/* Scenario Simulation & Alternative Dates */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Scenario Simulation */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Outcome Scenarios</CardTitle>
                <CardDescription>Expected outcomes based on timing</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {scenarioData.map((scenario) => (
                  <div key={scenario.scenario} className="space-y-2">
                    <div className="flex justify-between items-center">
                      <span className="text-sm font-medium">{scenario.scenario}</span>
                      <span className="text-sm font-bold">${scenario.revenue.toLocaleString()}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex-1 h-2 bg-muted rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-primary rounded-full transition-all"
                          style={{ width: `${scenario.probability}%` }}
                        />
                      </div>
                      <span className="text-xs text-muted-foreground">{scenario.probability}%</span>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Alternative Dates */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Alternative Launch Dates</CardTitle>
                <CardDescription>Secondary optimal windows</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {alternativeDates.map((alt, idx) => (
                  <div key={idx} className="p-3 bg-muted/50 rounded-lg space-y-1">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-medium">{alt.date}</p>
                        <p className="text-xs text-muted-foreground">{alt.reason}</p>
                      </div>
                      <div className="text-right">
                        <p className="font-bold">${alt.revenue.toLocaleString()}</p>
                        <p className={`text-xs ${alt.impactDelta < 0 ? 'text-red-600' : 'text-green-600'}`}>
                          {alt.impactDelta}% vs optimal
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>

          {/* AI Alerts */}
          <Card className="border-amber-500/50 bg-amber-50/50 dark:bg-amber-950/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-amber-700 dark:text-amber-400">
                <AlertCircle className="h-5 w-5" />
                Dynamic Market Alerts
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <div className="flex items-start gap-2 text-sm">
                <div className="h-2 w-2 rounded-full bg-amber-500 mt-1.5 flex-shrink-0" />
                <p><strong>Competitor Alert:</strong> Major competitor planning launch Week 6. Optimal window remains Week 3.</p>
              </div>
              <div className="flex items-start gap-2 text-sm">
                <div className="h-2 w-2 rounded-full bg-green-500 mt-1.5 flex-shrink-0" />
                <p><strong>Market Opportunity:</strong> Consumer sentiment trending 15% higher than forecasted for Week 3.</p>
              </div>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
